baseURL = 'https://berembagh.tk/'
languageCode = 'en-us'
title = 'Berem?!'
# theme
theme = 'ananke'
# post pagination
paginate = "10"
# post excerpt
summaryLength = "10"

######################### Default Parameters ###########################
[params]
# logo
# logo = "images/navlogo.png"
# logoWidth = 248
# logoHeight = 50
# favicon
# favicon = "images/favicon.png"
# meta data
author = "Madness"
description = "Having Fun"
# homepage main section
mainSections = ["posts"]
# contact form action
# contact_form_action = "#" # contact form works with : https://formspree.io
# copyright
copyright = ""
rssLimit = 20
# search *** true or false (if Search is disable Menu will align in Right) ***
search = true

header_search_layout = "expanded" # "expanded" or "popupable"
# Menu align *** "left", "right" or "center" (if Search is disable Menu will align in Right) ***
menu_align = "center"
# Blog-details page sidebar
sidebar = "right" # Sidebar value ("left", "right" or false)

# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX

code_copy_button = true # Turn on/off the code-copy-button for code-fields

######################## Site Variables #########################
[params.variables]
# Color Variables
primary_color = "#47c4f1"
secondary_color = "#9AC4F8"
text_color = "#666666"
text_color_dark = "#222222"
body_color = "#fff"
border_color = "#ACB9C4"
black = "#000"
white = "#fff"
light = "#F8F8F8"

# font variable
# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
primary_font = "PT Sans:wght@400;700"
secondary_font = ""
icon_font = "Font Awesome 5 Free"
