baseURL = 'www.berembagh.tk'
languageCode = 'en-us'
title = 'MadeMad'

theme = 'poison'

[Params]
    brand = "Home"                       # name of your site - appears in the sidebar
    #brand_image = "/images/test.jpg"    # path to the image shown in the sidebar
    #description = "Update this description..." # Used as default meta description if not specified in front matter
    dark_mode = true                      # optional - defaults to false
    favicon = "favicon.png"             # path to favicon (defaults to favicon.png)

    front_page_content = ["posts", "scripts"]

    menu = [
        {Name = "Posts", URL = "/posts/", HasChildren = true, Limit = 5},
        {Name = "Scripts", URL = "/scripts/", HasChildren = "true", Limit = "1"},
        {Name = "Categories", URL = "/categories/", HasChildren = false},
        {Name = "Tags", URL = "/tags/", HasChildren = false},
    ]

    rss_icon = true
    rss_section = "posts"